version: "3.7"
services:
  programmeplumealoup:
    build: .
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80
    expose : 
      - 80 
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.programmeplumealoup.tls.certresolver=myresolver
      - traefik.http.routers.programmeplumealoup.tls=true
      - traefik.http.routers.programmeplumealoup.rule=Host(`programme.laplumealoup.fr`)
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external: true
